# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!


class OrdersStub:
    """Generated client marker for the orders service."""

    def __init__(self, channel):
        self.GetOrder = channel.unary_unary(
            "/commerce.orders.v1.Orders/GetOrder"
        )
