//! Portable Agent Plugin generation and developer-local workspace binding.

mod composition;
mod filesystem;
mod render;

use std::collections::BTreeMap;
use std::fs;
use std::io::Read as _;
use std::path::{Path, PathBuf};

use code_system_graph_core::ExitCode;
use code_system_graph_model::OverallFreshness;
pub use composition::uninstall_composed_integration;
use composition::{install_composed_integration, validate_composed_base};
use filesystem::{
    replace_owned_atomically, verify_binding_ownership, verify_existing, write_new_atomically
};
use render::{render_files, workspace_component_name};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{ApplicationError, application_exit_code, status_workspace};

const BINDING_GENERATOR: &str = "csgraph plugin binding";
const LEGACY_COMPOSE_GENERATOR: &str = "csgraph plugin compose";
const BINDING_RELATIVE_PATH: &str = ".local/code-system-graph/mcp-binding.json";
const INTEGRATION_RECEIPT_RELATIVE_PATH: &str = ".local/code-system-graph/plugin-integration.json";

/// Inputs accepted by `csgraph plugin create`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentPluginCreateRequest {
    /// Workspace manifest to validate and bind.
    pub config: PathBuf,
    /// Existing graph database containing the workspace snapshot.
    pub database: PathBuf,
    /// Type-safe generation target.
    pub target: AgentPluginCreateTarget,
    /// Expose optional read-only CodeGraph-backed MCP tools.
    pub codegraph: bool,
    /// Optional absolute or resolvable `CodeGraph` executable.
    pub codegraph_binary: Option<PathBuf>,
}

/// Mutually exclusive output modes accepted by [`create_agent_plugin`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AgentPluginCreateTarget {
    /// Generate or verify a complete portable plugin directory.
    Complete {
        /// New or already-identical output directory.
        output: PathBuf,
    },
    /// Compose a managed integration into an existing portable plugin.
    Existing {
        /// Existing portable plugin root.
        output: PathBuf,
        /// MCP server entry to add or verify.
        mcp_server_name: String,
        /// Routing skill to add or verify.
        routing_skill: String,
        /// Replace an older local receipt and binding generated by `plugin create`.
        replace_generated: bool,
    },
}

/// Output mode selected by `csgraph plugin create`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AgentPluginCreateMode {
    /// Generate or verify the complete portable plugin.
    CompletePlugin,
    /// Add or verify one managed integration in an existing plugin.
    ExistingPlugin,
}

/// Machine-readable report returned after plugin generation or verification.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct AgentPluginCreateReport {
    /// Report schema version.
    pub schema_version: u8,
    /// Whether a complete plugin or only an existing plugin binding was created.
    pub mode: AgentPluginCreateMode,
    /// Workspace bound into the plugin.
    pub workspace: String,
    /// Stable workspace-specific plugin identity.
    pub plugin_name: String,
    /// Stable workspace-specific MCP server entry name.
    pub mcp_server_name: String,
    /// Stable workspace-specific skill name.
    pub skill_name: String,
    /// Canonical directory containing the workspace manifest.
    pub workspace_root: String,
    /// Client-managed activation semantics available in Agent Plugins 1.0.0.
    pub activation_scope: String,
    /// Absolute graph database path stored in the ignored local binding.
    pub database: String,
    /// Absolute generated plugin directory.
    pub output: String,
    /// Absolute ignored runtime binding file.
    pub binding: String,
    /// Whether the generated MCP enables `CodeGraph`.
    pub codegraph_enabled: bool,
    /// Absolute `CodeGraph` executable, when explicitly configured.
    pub codegraph_binary: Option<String>,
    /// Snapshot freshness observed during preflight.
    pub snapshot_freshness: OverallFreshness,
    /// Deterministic generated file list.
    pub files: Vec<String>,
    /// Whether a new plugin or binding was written, or an owned binding was replaced.
    pub changed: bool,
}

/// Inputs accepted by `csgraph plugin uninstall` for a composed plugin.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentPluginUninstallRequest {
    /// Existing portable plugin root.
    pub output: PathBuf,
    /// Managed MCP server entry to remove.
    pub mcp_server_name: String,
    /// Managed routing skill to remove.
    pub routing_skill: String,
}

/// Machine-readable report returned after removing a managed integration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct AgentPluginUninstallReport {
    /// Report schema version.
    pub schema_version: u8,
    /// Portable plugin name that retained ownership of all unrelated content.
    pub plugin_name: String,
    /// Removed MCP server entry.
    pub mcp_server_name: String,
    /// Removed routing skill.
    pub skill_name: String,
    /// Canonical plugin root.
    pub output: String,
    /// Deterministic list of removed managed paths.
    pub removed: Vec<String>,
    /// Whether managed content was removed.
    pub changed: bool,
}

/// Local runtime policy consumed by `csgraph mcp --binding`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct AgentPluginMcpBinding {
    /// Binding format version.
    pub schema_version: u8,
    /// Ownership identity.
    pub generator: String,
    /// Exact build that materialized this local binding, when recorded by a recent generator.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generator_build: Option<AgentPluginGeneratorBuild>,
    /// Portable plugin name that owns the binding.
    pub base_plugin_name: String,
    /// Canonical portable plugin root used when creating the binding.
    pub base: String,
    /// Workspace configured for the MCP process.
    pub workspace: String,
    /// Canonical workspace manifest used when creating the binding.
    pub config: String,
    /// Canonical graph database opened by the MCP process.
    pub database: String,
    /// Whether read-only `CodeGraph` enrichment is enabled.
    pub codegraph_enabled: bool,
    /// Canonical `CodeGraph` executable, when explicitly configured.
    pub codegraph_binary: Option<String>,
}

/// Auditable identity of the `csgraph` executable that materialized local plugin state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct AgentPluginGeneratorBuild {
    /// Code System Graph package version.
    pub version: String,
    /// Source commit embedded at build time, when the build environment exposed one.
    pub source_commit: Option<String>,
    /// Whether the source checkout was dirty when the executable was built, when known.
    pub source_dirty: Option<bool>,
    /// BLAKE3 fingerprint of the exact executable that ran `plugin create`.
    pub binary_fingerprint: String,
}

/// Failure while generating or binding an Agent Plugin.
#[derive(Debug, Error)]
pub enum AgentPluginError {
    /// Manifest, database, or freshness validation failed.
    #[error(transparent)]
    Application(Box<ApplicationError>),
    /// A required path could not be resolved.
    #[error("failed to resolve `{path}`: {source}")]
    Resolve {
        /// Input path.
        path: PathBuf,
        /// Operating-system failure.
        #[source]
        source: std::io::Error,
    },
    /// A path cannot be represented portably in JSON or Markdown.
    #[error("path `{0}` is not valid Unicode")]
    NonUnicodePath(PathBuf),
    /// A canonical workspace manifest unexpectedly has no containing directory.
    #[error("workspace manifest `{0}` has no containing workspace root")]
    MissingWorkspaceRoot(PathBuf),
    /// Existing path is not byte-for-byte identical to the requested generated content.
    #[error("plugin path `{output}` conflicts with the requested content: {detail}")]
    Conflict {
        /// Output directory.
        output: PathBuf,
        /// Bounded conflict explanation.
        detail: String,
    },
    /// Plugin content could not be written atomically.
    #[error("failed to write plugin content `{path}`: {source}")]
    Write {
        /// Affected path.
        path: PathBuf,
        /// Operating-system failure.
        #[source]
        source: std::io::Error,
    },
    /// Generated JSON could not be serialized.
    #[error("failed to serialize `{file}`: {source}")]
    Json {
        /// Generated file.
        file: &'static str,
        /// Serialization failure.
        #[source]
        source: serde_json::Error,
    },
    /// Base plugin JSON is valid JSON but has an unsupported shape.
    #[error("base plugin file `{file}` is invalid: {detail}")]
    InvalidBase {
        /// Relative plugin file.
        file: &'static str,
        /// Bounded validation explanation.
        detail: String,
    },
    /// A versioned Agent Plugin template is malformed or has an invalid variable contract.
    #[error("agent plugin template `{file}` is invalid: {detail}")]
    Template {
        /// Template path relative to `agent-integration-template/agent-plugin`.
        file: &'static str,
        /// Bounded validation explanation.
        detail: String,
    },
    /// Command options select an incomplete or unsupported creation mode.
    #[error("invalid plugin create request: {0}")]
    InvalidRequest(String),
}

impl From<ApplicationError> for AgentPluginError {
    fn from(error: ApplicationError) -> Self {
        Self::Application(Box::new(error))
    }
}

/// Classifies plugin failures into stable process exit codes.
#[must_use]
pub fn agent_plugin_exit_code(error: &AgentPluginError) -> ExitCode {
    match error {
        AgentPluginError::Application(source) => application_exit_code(source),
        AgentPluginError::Resolve { source, .. }
            if source.kind() == std::io::ErrorKind::NotFound =>
        {
            ExitCode::NotFound
        }
        AgentPluginError::Conflict { .. } => ExitCode::Conflict,
        AgentPluginError::NonUnicodePath(_)
        | AgentPluginError::InvalidBase { .. }
        | AgentPluginError::Template { .. }
        | AgentPluginError::InvalidRequest(_)
        | AgentPluginError::Json { .. } => ExitCode::InvalidInput,
        AgentPluginError::Resolve { .. }
        | AgentPluginError::MissingWorkspaceRoot(_)
        | AgentPluginError::Write { .. } => ExitCode::Internal,
    }
}

/// Creates or verifies an Agent Plugins 1.0.0 package for one workspace.
///
/// Without integration options, the complete package is rendered in memory and new output is
/// assembled atomically. When both an MCP server and routing skill are specified, the output must
/// be an existing portable plugin. Missing managed MCP entries and skill files are added while
/// unrelated components are preserved. An ignored receipt enables safe removal with
/// [`uninstall_composed_integration`].
///
/// # Errors
///
/// Returns [`AgentPluginError`] for an invalid manifest/database pair, unsafe existing output,
/// path resolution failure, or non-atomic write failure.
pub fn create_agent_plugin(
    request: &AgentPluginCreateRequest,
) -> Result<AgentPluginCreateReport, AgentPluginError> {
    let config = canonicalize_file(&request.config)?;
    let database = canonicalize_file(&request.database)?;
    let codegraph_binary = request
        .codegraph_binary
        .as_ref()
        .map(|path| canonicalize_file(path))
        .transpose()?;
    if codegraph_binary.is_some() && !request.codegraph {
        return Err(AgentPluginError::Template {
            file: "mcp-binding.json",
            detail: "an explicit CodeGraph binary requires the CodeGraph profile".to_owned(),
        });
    }
    let status = status_workspace(&config, &database)?;
    let workspace_root = config
        .parent()
        .ok_or_else(|| AgentPluginError::MissingWorkspaceRoot(config.clone()))?
        .to_path_buf();
    let generated_component = workspace_component_name(&status.workspace);
    let (mode, output, plugin_name, mcp_server_name, skill_name, replace_generated) =
        match &request.target {
            AgentPluginCreateTarget::Existing {
                output,
                mcp_server_name: server,
                routing_skill: skill,
                replace_generated,
            } => {
                let output = canonicalize_directory(output)?;
                let plugin_name = validate_composed_base(&output, server, skill)?;
                (
                    AgentPluginCreateMode::ExistingPlugin,
                    output,
                    plugin_name,
                    server.to_owned(),
                    skill.to_owned(),
                    *replace_generated,
                )
            }
            AgentPluginCreateTarget::Complete { output } => (
                AgentPluginCreateMode::CompletePlugin,
                absolute_output_path(output)?,
                generated_component.clone(),
                generated_component.clone(),
                generated_component,
                false,
            ),
        };
    let binding = AgentPluginMcpBinding {
        schema_version: 1,
        generator: BINDING_GENERATOR.to_owned(),
        generator_build: Some(generator_build_metadata()?),
        base_plugin_name: plugin_name.clone(),
        base: unicode_path(&output)?,
        workspace: status.workspace.clone(),
        config: unicode_path(&config)?,
        database: unicode_path(&database)?,
        codegraph_enabled: request.codegraph,
        codegraph_binary: codegraph_binary.as_deref().map(unicode_path).transpose()?,
    };
    let (reported_files, changed) = if mode == AgentPluginCreateMode::ExistingPlugin {
        install_composed_integration(
            &output,
            &plugin_name,
            &status.workspace,
            &mcp_server_name,
            &skill_name,
            &binding,
            replace_generated,
        )?
    } else {
        let files = render_files(&status.workspace, &plugin_name, &binding)?;
        let changed = if fs::symlink_metadata(&output).is_ok() {
            verify_existing(&output, &files)?;
            false
        } else {
            write_new_atomically(&output, &files)?;
            true
        };
        (files.keys().cloned().collect(), changed)
    };

    Ok(AgentPluginCreateReport {
        schema_version: 1,
        mode,
        workspace: status.workspace,
        plugin_name,
        mcp_server_name,
        skill_name,
        workspace_root: unicode_path(&workspace_root)?,
        activation_scope: "client_managed_project_local".to_owned(),
        database: unicode_path(&database)?,
        output: unicode_path(&output)?,
        binding: unicode_path(&output.join(BINDING_RELATIVE_PATH))?,
        codegraph_enabled: request.codegraph,
        codegraph_binary: codegraph_binary.as_deref().map(unicode_path).transpose()?,
        snapshot_freshness: status.freshness.overall,
        files: reported_files,
        changed,
    })
}

fn generator_build_metadata() -> Result<AgentPluginGeneratorBuild, AgentPluginError> {
    let executable = std::env::current_exe().map_err(|source| AgentPluginError::Resolve {
        path: PathBuf::from("<current csgraph executable>"),
        source,
    })?;
    let mut file = fs::File::open(&executable).map_err(|source| AgentPluginError::Resolve {
        path: executable.clone(),
        source,
    })?;
    let mut hasher = blake3::Hasher::new();
    let mut buffer = [0_u8; 8 * 1024];
    loop {
        let read = file
            .read(&mut buffer)
            .map_err(|source| AgentPluginError::Resolve {
                path: executable.clone(),
                source,
            })?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(AgentPluginGeneratorBuild {
        version: env!("CARGO_PKG_VERSION").to_owned(),
        source_commit: option_env!("CODE_SYSTEM_GRAPH_BUILD_GIT_COMMIT").map(str::to_owned),
        source_dirty: option_env!("CODE_SYSTEM_GRAPH_BUILD_GIT_DIRTY")
            .and_then(|value| value.parse().ok()),
        binary_fingerprint: format!("blake3:{}", hasher.finalize().to_hex()),
    })
}

/// Loads and validates a local binding for `csgraph mcp --binding`.
///
/// # Errors
///
/// Returns [`AgentPluginError`] when the file is missing, malformed, not generated by the
/// supported local-binding contract, or references unavailable runtime files.
pub fn load_agent_plugin_mcp_binding(
    path: &Path,
) -> Result<AgentPluginMcpBinding, AgentPluginError> {
    require_regular_file(path, "binding must be a regular file, not a symlink")?;
    let path = canonicalize_file(path)?;
    let mut binding: AgentPluginMcpBinding = serde_json::from_slice(&fs::read(&path).map_err(
        |source| AgentPluginError::Resolve {
            path: path.clone(),
            source,
        },
    )?)
    .map_err(|source| AgentPluginError::Json {
        file: "mcp-binding.json",
        source,
    })?;
    if binding.schema_version != 1 || !recognized_binding_generator(&binding.generator) {
        return Err(conflict(
            &path,
            "binding ownership identity is not recognized",
        ));
    }
    validate_component_name(&binding.base_plugin_name, "base plugin")?;
    if binding.workspace.trim().is_empty() {
        return Err(AgentPluginError::InvalidBase {
            file: "mcp-binding.json",
            detail: "`workspace` must be non-empty".to_owned(),
        });
    }
    binding.config = unicode_path(&canonicalize_file(Path::new(&binding.config))?)?;
    binding.database = unicode_path(&canonicalize_file(Path::new(&binding.database))?)?;
    binding.codegraph_binary = binding
        .codegraph_binary
        .as_deref()
        .map(Path::new)
        .map(canonicalize_file)
        .transpose()?
        .as_deref()
        .map(unicode_path)
        .transpose()?;
    if binding.codegraph_binary.is_some() && !binding.codegraph_enabled {
        return Err(AgentPluginError::InvalidBase {
            file: "mcp-binding.json",
            detail: "`codegraphBinary` requires `codegraphEnabled`".to_owned(),
        });
    }
    Ok(binding)
}

fn binding_files(
    binding: &AgentPluginMcpBinding,
) -> Result<BTreeMap<String, Vec<u8>>, AgentPluginError> {
    let mut files = BTreeMap::new();
    files.insert(
        "mcp-binding.json".to_owned(),
        pretty_json(
            "mcp-binding.json",
            &serde_json::to_value(binding).map_err(|source| AgentPluginError::Json {
                file: "mcp-binding.json",
                source,
            })?,
        )?,
    );
    Ok(files)
}

fn write_local_binding(
    base: &Path,
    files: &BTreeMap<String, Vec<u8>>,
    replace_generated: bool,
) -> Result<bool, AgentPluginError> {
    let local_parent = base.join(".local");
    ensure_local_parent(&local_parent)?;
    let output = base.join(".local/code-system-graph");
    if fs::symlink_metadata(&output).is_err() {
        write_new_atomically(&output, files)?;
        return Ok(true);
    }

    let metadata = fs::symlink_metadata(&output).map_err(|source| AgentPluginError::Resolve {
        path: output.clone(),
        source,
    })?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(conflict(
            &output,
            "generated binding root must be a real directory",
        ));
    }
    match verify_existing(&output, files) {
        Ok(()) => Ok(false),
        Err(_) if replace_generated => {
            verify_binding_ownership(&output)?;
            replace_owned_atomically(&output, files)?;
            Ok(true)
        }
        Err(error) => Err(error),
    }
}

fn recognized_binding_generator(generator: &str) -> bool {
    generator == BINDING_GENERATOR || generator == LEGACY_COMPOSE_GENERATOR
}

fn read_json_file(path: &Path, file: &'static str) -> Result<serde_json::Value, AgentPluginError> {
    serde_json::from_slice(&fs::read(path).map_err(|source| AgentPluginError::Resolve {
        path: path.to_path_buf(),
        source,
    })?)
    .map_err(|source| AgentPluginError::Json { file, source })
}

fn require_regular_file(path: &Path, detail: &str) -> Result<(), AgentPluginError> {
    let metadata = fs::symlink_metadata(path).map_err(|_| conflict(path, detail))?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(conflict(path, detail));
    }
    Ok(())
}

fn ensure_local_parent(path: &Path) -> Result<(), AgentPluginError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
            Err(conflict(path, "`.local` must be a real directory"))
        }
        Ok(_) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            fs::create_dir(path).map_err(|source| AgentPluginError::Write {
                path: path.to_path_buf(),
                source,
            })
        }
        Err(source) => Err(AgentPluginError::Resolve {
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn canonicalize_file(path: &Path) -> Result<PathBuf, AgentPluginError> {
    let canonical = fs::canonicalize(path).map_err(|source| AgentPluginError::Resolve {
        path: path.to_path_buf(),
        source,
    })?;
    let metadata = fs::metadata(&canonical).map_err(|source| AgentPluginError::Resolve {
        path: path.to_path_buf(),
        source,
    })?;
    if !metadata.is_file() {
        return Err(AgentPluginError::Conflict {
            output: path.to_path_buf(),
            detail: "expected a regular file".to_owned(),
        });
    }
    Ok(canonical)
}

fn absolute_output_path(path: &Path) -> Result<PathBuf, AgentPluginError> {
    if let Ok(metadata) = fs::symlink_metadata(path) {
        if metadata.file_type().is_symlink() {
            return Err(conflict(path, "output must not be a symlink"));
        }
        return fs::canonicalize(path).map_err(|source| AgentPluginError::Resolve {
            path: path.to_path_buf(),
            source,
        });
    }
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    let parent = fs::canonicalize(parent).map_err(|source| AgentPluginError::Resolve {
        path: parent.to_path_buf(),
        source,
    })?;
    let name = path.file_name().ok_or_else(|| AgentPluginError::Conflict {
        output: path.to_path_buf(),
        detail: "output must name a directory below an existing parent".to_owned(),
    })?;
    Ok(parent.join(name))
}

fn canonicalize_directory(path: &Path) -> Result<PathBuf, AgentPluginError> {
    let canonical = fs::canonicalize(path).map_err(|source| AgentPluginError::Resolve {
        path: path.to_path_buf(),
        source,
    })?;
    let metadata = fs::metadata(&canonical).map_err(|source| AgentPluginError::Resolve {
        path: path.to_path_buf(),
        source,
    })?;
    if !metadata.is_dir() {
        return Err(conflict(path, "expected a directory"));
    }
    Ok(canonical)
}

fn required_json_string<'a>(
    document: &'a serde_json::Value,
    file: &'static str,
    field: &str,
) -> Result<&'a str, AgentPluginError> {
    document
        .get(field)
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| AgentPluginError::InvalidBase {
            file,
            detail: format!("`{field}` must be a non-empty string"),
        })
}

fn validate_component_name(value: &str, kind: &str) -> Result<(), AgentPluginError> {
    let valid = !value.is_empty()
        && value.len() <= 64
        && value.starts_with(|character: char| character.is_ascii_lowercase())
        && value.ends_with(|character: char| {
            character.is_ascii_lowercase() || character.is_ascii_digit()
        })
        && value.chars().all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        });
    if !valid {
        return Err(AgentPluginError::InvalidBase {
            file: "plugin.json",
            detail: format!("{kind} `{value}` is not a valid lower-case component name"),
        });
    }
    Ok(())
}

fn pretty_json(file: &'static str, value: &serde_json::Value) -> Result<Vec<u8>, AgentPluginError> {
    let mut bytes = serde_json::to_vec_pretty(value)
        .map_err(|source| AgentPluginError::Json { file, source })?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn conflict(output: &Path, detail: &str) -> AgentPluginError {
    AgentPluginError::Conflict {
        output: output.to_path_buf(),
        detail: detail.to_owned(),
    }
}

fn unicode_path(path: &Path) -> Result<String, AgentPluginError> {
    path.to_str()
        .map(ToOwned::to_owned)
        .ok_or_else(|| AgentPluginError::NonUnicodePath(path.to_path_buf()))
}
